# Generated by Django 5.2.17 on 2026-09-04 16:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study_core", "0002_dailyquiz_dailyquestion_dailyquizsession"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyquestion",
            name="category",
            field=models.CharField(
                choices=[
                    ("current_affairs", "Current Affairs"),
                    ("gk", "General Knowledge"),
                ],
                default="gk",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dailyquestion",
            name="difficulty_tier",
            field=models.CharField(
                blank=True,
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                help_text="Static difficulty for GK questions (None for Current Affairs).",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="current_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gk_skill_tier",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="medium",
                help_text="Adaptive GK difficulty tier served to this user.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_quiz_completed_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="longest_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="dailyquestion",
            index=models.Index(
                fields=["quiz", "category", "difficulty_tier"],
                name="study_core__quiz_id_f00f49_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["current_streak", "longest_streak"],
                name="study_core__current_350369_idx",
            ),
        ),
    ]
