# Generated by Django 5.2.17 on 2026-09-04 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study_core", "0004_userprofile_bio_avatar_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blocker",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when status=blocked — the user who issued the block.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="friendship_blocks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "initiator",
                    models.ForeignKey(
                        help_text="User who sent the request (or who performed the block).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendship_initiated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendship_as_receiver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendship_as_sender",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["sender", "status"],
                        name="study_core__sender__35260c_idx",
                    ),
                    models.Index(
                        fields=["receiver", "status"],
                        name="study_core__receive_585a34_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sender", "receiver"), name="uniq_friendship_pair"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sender_id__lt", models.F("receiver_id"))),
                        name="friendship_canonical_order",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="QuizChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "question_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Ordered snapshot of question UUIDs the challenged user must answer.",
                    ),
                ),
                ("challenger_score", models.IntegerField(default=0)),
                ("challenged_score", models.IntegerField(blank=True, null=True)),
                ("challenger_time_seconds", models.FloatField(default=0.0)),
                ("challenged_time_seconds", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "challenged_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duels_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "challenger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duels_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quiz_challenges",
                        to="study_core.document",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        help_text="Challenger's completed adaptive session (the quiz instance).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quiz_challenges",
                        to="study_core.testsession",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duels_won",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["challenged_user", "status"],
                        name="study_core__challen_9bd616_idx",
                    ),
                    models.Index(
                        fields=["challenger", "status"],
                        name="study_core__challen_b07205_idx",
                    ),
                    models.Index(
                        fields=["status", "expires_at"],
                        name="study_core__status_1e54a2_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("session", "challenged_user"),
                        name="uniq_pending_challenge_pair",
                    )
                ],
            },
        ),
    ]
