# Generated by Django 5.2.17 on 2026-09-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study_core", "0005_friendship_quizchallenge"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testsession",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AddField(
            model_name="testsession",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
