# Generated by Django 5.2.17 on 2026-09-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study_core", "0006_alter_testsession_options_testsession_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizchallenge",
            name="document_filename",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Denormalised source document name shown in duel lists.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="quizchallenge",
            name="question_data",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Self-contained ordered snapshot of the duel questions [{id, question_text, options, correct_index}] — grading is independent of the originating document stack.",
            ),
        ),
        migrations.AlterField(
            model_name="quizchallenge",
            name="question_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Ordered snapshot of question ids the challenged user must answer.",
            ),
        ),
    ]
