# Generated by Django 5.2.17 on 2026-09-05 11:54

from django.db import migrations, models
from django.db.models import F


# Move every stored rating/difficulty from the old 1200-centered scale to the
# 0-based scale (new = old − 1200). Elo maths are difference-based, so the
# shift preserves every expected score / update — only the displayed numbers
# and the new-user starting point change. NULL end_elo stays NULL.
SHIFT = 1200.0

DATA_SHIFTS = [
    ("userprofile", ("elo_rating",)),
    ("question", ("difficulty_rating",)),
    ("testsession", ("start_elo", "end_elo")),
    ("sessionresponse", ("user_elo_after", "question_elo_after")),
]


def shift_to_zero_based(apps, schema_editor):
    _shift(apps, -SHIFT)


def shift_to_old_scale(apps, schema_editor):
    _shift(apps, +SHIFT)


def _shift(apps, delta):
    for model_name, fields in DATA_SHIFTS:
        model = apps.get_model("study_core", model_name)
        for field in fields:
            model.objects.update(**{field: F(field) + delta})


class Migration(migrations.Migration):

    dependencies = [
        ("study_core", "0008_dailyquizanswer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="difficulty_rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="sessionresponse",
            name="question_elo_after",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="sessionresponse",
            name="user_elo_after",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="testsession",
            name="start_elo",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="elo_rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.RunPython(shift_to_zero_based, shift_to_old_scale),
    ]
