# Generated by Django 6.1 on 2026-09-05 20:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study_core", "0009_alter_question_difficulty_rating_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_served",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this question has been presented to the user.",
                    ),
                ),
                (
                    "is_answered",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user has answered this question.",
                    ),
                ),
                (
                    "order_served",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Order in which this question was served (1-indexed).",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["order_served"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="difficulty_tier",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="medium",
                help_text="Categorical difficulty tier for the 2N partition.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="testsession",
            name="current_elo",
            field=models.FloatField(
                default=0.0, help_text="Real-time Elo rating during the session."
            ),
        ),
        migrations.AddField(
            model_name="testsession",
            name="current_question",
            field=models.ForeignKey(
                blank=True,
                help_text="The question currently being displayed to the user (for resume).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="currently_served_in_session",
                to="study_core.question",
            ),
        ),
        migrations.AddField(
            model_name="testsession",
            name="current_theta",
            field=models.FloatField(
                default=0.0, help_text="Real-time IRT ability parameter theta."
            ),
        ),
        migrations.AddField(
            model_name="testsession",
            name="generated_pool_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Size of the 2N LLM question pool (2 * requested_questions).",
            ),
        ),
        migrations.AddField(
            model_name="testsession",
            name="initial_predicted_level",
            field=models.CharField(
                blank=True,
                help_text="Initial ML prediction: Beginner, Intermediate, or Advanced.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="testsession",
            name="requested_questions",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="N the user requested to answer (3-50). Null = legacy mode.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="testsession",
            name="served_question_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of questions served/answered in this session.",
            ),
        ),
        migrations.AddField(
            model_name="testsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("abandoned", "Abandoned"),
                ],
                default="in_progress",
                help_text="Session status: in_progress, completed, or abandoned.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="testsession",
            name="is_completed",
            field=models.BooleanField(
                default=False,
                help_text='DEPRECATED: Use status field. True when status="completed".',
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["difficulty_tier"], name="study_core__difficu_320544_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testsession",
            index=models.Index(
                fields=["status", "user"], name="study_core__status_01d99d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionresponse",
            constraint=models.UniqueConstraint(
                fields=("session", "question"), name="uniq_session_question_once"
            ),
        ),
        migrations.AddField(
            model_name="sessionquestion",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_pool_entries",
                to="study_core.question",
            ),
        ),
        migrations.AddField(
            model_name="sessionquestion",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pool_questions",
                to="study_core.testsession",
            ),
        ),
        migrations.AddIndex(
            model_name="sessionquestion",
            index=models.Index(
                fields=["session", "is_served", "is_answered"],
                name="study_core__session_a45791_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sessionquestion",
            unique_together={("session", "question")},
        ),
    ]
