# Generated by Django 6.1 on 2026-09-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study_core", "0010_add_session_question_model_and_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testsession",
            name="generated_pool_count",
        ),
        migrations.RemoveField(
            model_name="testsession",
            name="served_question_count",
        ),
        migrations.AddField(
            model_name="testsession",
            name="questions_answered_count",
            field=models.IntegerField(
                default=0,
                help_text="How many questions this user has actually answered in this session.",
            ),
        ),
        migrations.AddField(
            model_name="testsession",
            name="questions_generated_count",
            field=models.IntegerField(
                default=0,
                help_text="Size of the raw 2N LLM question pool for this session.",
            ),
        ),
    ]
