# Generated by Django 5.2.17 on 2026-09-06 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_core', '0011_remove_testsession_generated_pool_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSessionState',
            fields=[
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='adaptive_state', serialize=False, to='study_core.testsession')),
                ('active_sub_tier', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=10)),
                ('consecutive_correct', models.IntegerField(default=0)),
                ('consecutive_wrong', models.IntegerField(default=0)),
                ('served_question_ids', models.JSONField(default=list)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sessionquestion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sessionquestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='sessionquestion',
            name='session',
        ),
        migrations.RemoveConstraint(
            model_name='sessionresponse',
            name='uniq_session_question_once',
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='study_core__difficu_320544_idx',
        ),
        migrations.RemoveIndex(
            model_name='testsession',
            name='study_core__status_01d99d_idx',
        ),
        migrations.RemoveField(
            model_name='question',
            name='difficulty_tier',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='current_elo',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='current_question',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='current_theta',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='initial_predicted_level',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='questions_answered_count',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='questions_generated_count',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='status',
        ),
        migrations.AddField(
            model_name='testsession',
            name='generated_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testsession',
            name='persona_tier',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='accuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avg_time_per_question',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_elo_rating',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='easy_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hard_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='medium_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='persona_predicted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='persona_tier',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], db_index=True, default='Beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='previous_avg_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='question_difficulty_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='questions_attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='quiz_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_answered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wrong_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sessionresponse',
            name='user_elo_after',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='requested_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='start_elo',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='elo_rating',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['persona_tier', 'elo_rating'], name='study_core__persona_d53142_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsessionstate',
            index=models.Index(fields=['active_sub_tier', 'is_completed'], name='study_core__active__8b4dc5_idx'),
        ),
        migrations.DeleteModel(
            name='SessionQuestion',
        ),
    ]
