# Generated by Django 5.2.17 on 2026-09-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study_core", "0015_archive_pages_tables"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sharedchallenge",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="sharedchallenge",
            name="document",
        ),
        migrations.RemoveField(
            model_name="testsession",
            name="challenge",
        ),
        migrations.RemoveIndex(
            model_name="testsession",
            name="study_core__challen_a20a1e_idx",
        ),
        migrations.RenameIndex(
            model_name="sessionresponse",
            new_name="study_core__session_cc7160_idx",
            old_name="study_core_session_i_d3a4bc_idx",
        ),
        migrations.AddConstraint(
            model_name="sessionresponse",
            constraint=models.UniqueConstraint(
                fields=("session", "question"), name="uniq_session_question_once"
            ),
        ),
        migrations.DeleteModel(
            name="SharedChallenge",
        ),
    ]
