# Generated by Django 5.2.17 on 2026-09-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_question_difficulty_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='consecutive_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testsession',
            name='consecutive_wrong',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testsession',
            name='current_sub_tier',
            field=models.CharField(default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='testsession',
            name='questions_answered_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='student_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_quizzes_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty_label',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
    ]
