# Generated by Django 5.2.17 on 2026-09-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_question_difficulty_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='questions_answered_count',
            field=models.IntegerField(default=0, help_text='How many questions this user has actually answered in this session.'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='questions_generated_count',
            field=models.IntegerField(default=0, help_text='Size of the raw 2N LLM question pool for this session.'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='requested_questions',
            field=models.IntegerField(blank=True, help_text='N the user requested to answer (None = legacy serve all generated).', null=True),
        ),
        migrations.AddConstraint(
            model_name='sessionresponse',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='uniq_session_question_once_pages'),
        ),
    ]
